version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_APP}
    command: sh -c "uv run occurrence_radar/manage.py migrate && uv run occurrence_radar/manage.py runserver 0.0.0.0:8000"
    ports:
      - "${PORT_APP}:8000"
    restart: unless-stopped
    pull_policy: build
    env_file:
      stack.env